### ISSUE TITLE
Can't click to active on rules section

### ISSUE THREAD

**Issue by mehmeh1z** [SebastianBecker2/PowerPlanSwitcher#34] opened 2024-10-07 22:32 UTC
I just can’t click activate in the rules section next to the application I added.
I tried reinstalling, installing older versions of the application, but nothing helped.

**Comment by SebastianBecker2** [comment] 2024-10-08 10:30
Sorry. This is a misunderstanding. The checkbox in the list of rules is supposed to show which rules are currently applied. It's a read-only column.
I will try to change it, to make it more clear.

**Comment by mehmeh1z** [comment] 2024-10-08 12:28
Yeah, now I understand why I couldn't click on it.
True, this does not change the fact that the power supply scheme does not change according to the given rules.
I tried all three trigger options for the .exe, but in none of them did the power scheme change after launching the .exe.

**Comment by SebastianBecker2** [comment] 2024-10-08 14:32
Interesting.
There certainly is a bug. Try restarting PowerPlanSwitcher after creating the rule you want.
It seems, new rules don't get processed when confirming the Settings dialog. Or something along those lines.

I will check this out and try to bring a fixed version asap. I hope restarting the app is a workaround for right now.

**Comment by SebastianBecker2** [comment] 2024-10-08 14:43
Just confirmed. It's a bug when changing the rules. The rule engine needs to be restarted with the new rules. This didn't happen since I renamed the property "PowerRules" to "Rules". But the I was still checking for "PowerRules" in the event handler.

I will publish a new version.

**Comment by SebastianBecker2** [comment] 2024-10-08 14:52
Here is the new release:
https://github.com/SebastianBecker2/PowerPlanSwitcher/releases/tag/v1.2.2.0

Sorry for the weird bug. I was mostly concerned with the rule engine working correctly when testing. In this case, the rule engine itself worked fine.

In case it's still not working, just reopen the issue. I will try my best to help.

**Comment by mehmeh1z** [comment] 2024-10-08 17:19
In the new version, automatic change of power plan still does not work.

**Comment by SebastianBecker2** [comment] 2024-10-08 18:21
Okay, maybe there is a different issue here. Can you try to select the Path/File from the active process using the "Select from active Process..." button?
![image](https://github.com/user-attachments/assets/658d08c5-75db-4647-8ab1-fbb5b24c4efa)
Maybe there is an issue with the image name or path.

And make sure you are on version 1.2.2.0. If the rule doesn't work. Try restarting PowerPlanSwitcher anyways. Maybe I screwed up the fix.

**Comment by SebastianBecker2** [comment] 2024-10-08 18:24
Btw: The active flag in the list of rules is not updated automatically. It gets loaded once when opening the dialog. Changes in activation of rules is not reflected until the Settings dialog is opened again.

**Comment by mehmeh1z** [comment] 2024-10-08 19:07
Yes, the application version is definitely the latest.
But in the selection of active processes there is no required process, although it is running.

**Comment by SebastianBecker2** [comment] 2024-10-09 15:20
If the process doesn't appear in the list of active processes, it makes sense that the rule isn't working.

There are some system processes that PowerPlanSwitcher can't properly access.

Can you tell me what process you're trying to react on? Maybe including the information from Task Manager. The Details view shows the name, PID, User name and Image path name. Those would be important to know.

Maybe I can find a way to get information about the process.

**Comment by mehmeh1z** [comment] 2024-10-10 00:55
I tried it with Genshin Impact
GenshinImpact.exe \ PID 6056 \ username is anon \ C:\Genshin\Genshin Impact game\GenshinImpact.exe
In fact, I no longer need a solution to this problem, because I made myself a simple .ps1 script to automatically change the power scheme.
Therefore, if no one else complains about this bug, then I think we can close the issue.
Sorry if I bothered you in vain.

**Comment by SebastianBecker2** [comment] 2024-10-10 06:41
You didn't bother me at all. I found at least one bug because of you.
And maybe I can figure out what the issue was. I have an idea.
I'm happy you have a solution.
I will keep the issue open while checking the hunch I have.

**Comment by SebastianBecker2** [comment] 2024-10-11 15:06
Never mind. My hunch got me nowhere.
I have no idea what the issue could be.

It's good that you have a solution that works for you. I will close the issue.
Maybe someone else will run into this again. That might give me more insights.

**Closed by SebastianBecker2** 2024-10-11 15:06 UTC

**Comment by wuguo138428** [comment] 2024-10-15 05:24
I think you can try to ask which country people, the nature of the system used, in my country with a lot of third-party personal streamlining system, resulting in missing features!
Some may even try to streamline into a pe system
________________________________
发件人: Sebastian Becker ***@***.***>
发送时间: 2024年10月11日 23:07
收件人: SebastianBecker2/PowerPlanSwitcher ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [SebastianBecker2/PowerPlanSwitcher] Can't click to active on rules section (Issue #34)


Closed #34<https://github.com/SebastianBecker2/PowerPlanSwitcher/issues/34> as completed.

―
